# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: my-agent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: 'docker build -t myimage .'
- task: CmdLine@2
  inputs:
    script: 'docker run -d --name mus-cont -p 1234:8000 myimage'
